### ISSUE TITLE
Is only jbuilder supported?

### ISSUE THREAD

**Issue by nekketsuuu** [gersonmoraes/dryunit#1]
I noticed that the `dryunit gen --framework alcotest` command may be assumed to be running under the directory `_build/default` (by default). So, is dryunit supposed to be used only with jbuilder? Can we utilize dryunit from the command line?

**Comment by gersonmoraes** [comment]
Hi, sorry for the huge waiting.

This limitation is actually to be run under a (sub)directory inside `build` or a `_build`. But that only made sense in the context of the ppx. I'll make the future version ignore this rule for the main generator. Currently they share code. I figure I assume most building systems would run `dryunit` under those conditions.

**Comment by gersonmoraes** [comment]
Since version 0.5 is out now and this restriction is gone, I'm closing this issue.
